/* -------------------------------------------------------------------------
   SCRIPT: tables.sql
   PHASE: III & V (Database Objects & Data)
   STUDENT: Bahati Theoneste (ID: 28497)
   PROJECT: Health Clinic Medicine Management System
   ------------------------------------------------------------------------- */

-- =========================================================
-- SECTION 1: CLEANUP (Drop old objects to start fresh)
-- =========================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ALERTS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE USAGE_LOG CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE STOCK_LEVEL CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE MEDICINE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL; -- Ignore if tables do not exist
END;
/

-- =========================================================
-- SECTION 2: TABLE CREATION
-- =========================================================

-- 1. MEDICINE Table (Parent Table)
-- Stores static details about drugs.
CREATE TABLE MEDICINE (
    medicine_id     NUMBER(10) PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    category        VARCHAR2(50),
    unit_price      NUMBER(10, 2),
    expiry_date     DATE NOT NULL,
    batch_no        VARCHAR2(50) UNIQUE,
    created_at      DATE DEFAULT SYSDATE
) TABLESPACE tbs_clinic_data;

-- 2. STOCK_LEVEL Table (Child Table)
-- Tracks current inventory quantity. One-to-One with Medicine.
CREATE TABLE STOCK_LEVEL (
    stock_id            NUMBER(10) PRIMARY KEY,
    medicine_id         NUMBER(10),
    quantity_available  NUMBER(10) CHECK (quantity_available >= 0),
    last_updated        DATE DEFAULT SYSDATE,
    CONSTRAINT fk_stock_med FOREIGN KEY (medicine_id) 
        REFERENCES MEDICINE(medicine_id) ON DELETE CASCADE
) TABLESPACE tbs_clinic_data;

-- 3. USAGE_LOG Table (Transaction History)
-- Records every time medicine is dispensed.
CREATE TABLE USAGE_LOG (
    log_id              NUMBER(10) PRIMARY KEY,
    medicine_id         NUMBER(10),
    quantity_used       NUMBER(10) NOT NULL,
    usage_date          DATE DEFAULT SYSDATE,
    patient_reference   VARCHAR2(50), 
    CONSTRAINT fk_usage_med FOREIGN KEY (medicine_id) 
        REFERENCES MEDICINE(medicine_id)
) TABLESPACE tbs_clinic_data;

-- 4. ALERTS Table (System Notifications)
-- Stores warnings generated by PL/SQL triggers.
CREATE TABLE ALERTS (
    alert_id        NUMBER(10) PRIMARY KEY,
    medicine_id     NUMBER(10),
    alert_type      VARCHAR2(20) CHECK (alert_type IN ('LOW_STOCK', 'EXPIRY')),
    alert_message   VARCHAR2(255),
    alert_date      DATE DEFAULT SYSDATE,
    status          VARCHAR2(20) DEFAULT 'NEW',
    CONSTRAINT fk_alert_med FOREIGN KEY (medicine_id) 
        REFERENCES MEDICINE(medicine_id)
) TABLESPACE tbs_clinic_data;

-- =========================================================
-- SECTION 3: DATA INSERTION (Test Data)
-- =========================================================

-- Medicine 1: Paracetamol (Normal Stock)
INSERT INTO MEDICINE VALUES (101, 'Paracetamol 500mg', 'Painkiller', 500, SYSDATE + 365, 'BATCH-001', SYSDATE);
INSERT INTO STOCK_LEVEL VALUES (1, 101, 500, SYSDATE);

-- Medicine 2: Amoxicillin (Expiring Soon - For testing alerts)
INSERT INTO MEDICINE VALUES (102, 'Amoxicillin 250mg', 'Antibiotic', 1200, SYSDATE + 20, 'BATCH-002', SYSDATE);
INSERT INTO STOCK_LEVEL VALUES (2, 102, 50, SYSDATE);

-- Medicine 3: Ibuprofen (Low Stock - Only 8 left!)
INSERT INTO MEDICINE VALUES (103, 'Ibuprofen 400mg', 'Painkiller', 600, SYSDATE + 180, 'BATCH-003', SYSDATE);
INSERT INTO STOCK_LEVEL VALUES (3, 103, 8, SYSDATE); 

-- Medicine 4: Coartem (Malaria Treatment)
INSERT INTO MEDICINE VALUES (104, 'Coartem 20/120', 'Antimalarial', 2500, SYSDATE + 60, 'BATCH-004', SYSDATE);
INSERT INTO STOCK_LEVEL VALUES (4, 104, 100, SYSDATE);

-- Medicine 5: Cetirizine (Allergy)
INSERT INTO MEDICINE VALUES (105, 'Cetirizine 10mg', 'Antihistamine', 300, SYSDATE + 400, 'BATCH-005', SYSDATE);
INSERT INTO STOCK_LEVEL VALUES (5, 105, 200, SYSDATE);

-- Commit all changes to save data
COMMIT;
